/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import Head from "next/head";
// import Link from "next/link";
// import { api } from "~/utils/api";
import Layout from "./components/Layout";

export default function Home() {
  // const conv = api.conversations.getConversationInfo.useQuery({
  //   convNumber: "1",
  // });

  return (
    <>
      <Head>
        <title>REU Data Tool</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      {/* <div>{conv.data ? conv.data.info : "loading"}</div> */}
      <Layout></Layout>
    </>
  );
}
